FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y g++ && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY main.cpp .
COPY httplib.h .
COPY index.html .

RUN g++ -std=c++17 -O2 main.cpp -o app

EXPOSE 8080

CMD ["./app"]